---
- name: "Restart Service"
  systemd:
    daemon_reload: "yes"
    name:          "cfssl@{{ item.fqdn }}.service"
    state:         "restarted"
  with_items: "{{ cfssl | default[] }}"
  listen: "cfssl-restart"
